name: Quality Checks
on: [push,pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: golangci-lint
        uses: actions-contrib/golangci-lint@v1
        run: make lint
        working-directory: ./Go