os: linux
dist: trusty
sudo: required
matrix:
  include:
    - language: csharp
      mono: none
      dotnet: 3.1.100
      before_script:
        - cd CSharp
      script:
        - dotnet build
        - dotnet test leetcodesln_test/leetcodesln_test.csproj

    - language: go
      before_script:
        - cd Go
      script:
        - go test ./...
        
notifications:
  email:
    recipients:
      - stan_gai@Hotmail.com
    on_success: never #default: change
    on_failure: always #default:always


  # or you can add [ci skip] into your commit's message eg: git commit -m "readme update [ci skip]"