name: Quality Checks
on: [push,pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: linting
        run: make lint
        working-directory: ./Go
        uses: actions-contrib/golangci-lint@v1