name: Github Actions
on: push

jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: pwd
        run: |
          git clone https://github.com/user3301/TrialOfTheGrasses
          ls
          pwd
          cd Go
          pwd
