name: Github Actions
on: push

jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1' # The Go version to download (if necessary) and use.
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.25.0
        working-directory: Go
      - run: golangci-lint run -v ./...
        working-directory: Go
        env:
          GO111MODULE: "on"
          GOFLAGS: "-mod=vendor"
