name: Quality Checks
on: [push,pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - work-directory: ./Go
      - name: Run golangci-lint
        uses: actions-contrib/golangci-lint@v1